---
- name: Create source directory
  file:
    path: "/usr/local/lib/golang-{{ golang_version }}"
    state: directory
    mode: 0755

- name: Download and extract the archive
  unarchive:
    src:
      "https://golang.org/dl/go{{ golang_version }}\
      .{{ golang_os }}-{{ golang_arch[ansible_architecture] }}.tar.gz"
    dest: "/usr/local/lib/golang-{{ golang_version }}"
    remote_src: true
    extra_opts:
      - '--strip-components=1'

- name: Create go link
  file:
    src: "/usr/local/lib/golang-{{ golang_version }}/bin/go"
    dest: /usr/local/bin/go
    state: link
